/************************************************************\
 **     Copyright (c) 2012-2023 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/EXU/Sobel/td/al_ip/hsyncfifo_2048x8.v
 ** Date	:	2024 07 11
 ** TD version	:	5.6.71036
\************************************************************/

`timescale 1ns / 1ps

module hsyncfifo_2048x8_afull1920 (
	rst,
	di, clk, we,
	do, re,
	empty_flag,
	full_flag, afull_flag 
);

	input rst;
	input [7:0] di;
	input clk, we;
	input re;

	output [7:0] do;
	output empty_flag;
	output full_flag, afull_flag;

EG_LOGIC_FIFO #(
 	.DATA_WIDTH_W(8),
	.DATA_WIDTH_R(8),
	.DATA_DEPTH_W(2048),
	.DATA_DEPTH_R(2048),
	.ENDIAN("LITTLE"),
	.RESETMODE("ASYNC"),
	.E(0),
	.F(2048),
	.ASYNC_RESET_RELEASE("ASYNC"),
	.AF(1919))
fifo_inst(
	.rst(rst),
	.di(di),
	.clkw(clk),
	.we(we),
	.csw(3'b111),
	.do(do),
	.clkr(clk),
	.re(re),
	.csr(3'b111),
	.ore(1'b0),
	.empty_flag(empty_flag),
	.aempty_flag(),
	.full_flag(full_flag),
	.afull_flag(afull_flag)

);

endmodule