--------------------------------------------------------------
 --     Copyright (c) 2012-2023 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	//wsl.localhost/Ubuntu-20.04/home/superior/Sobel/td/sobel_ctrl/al_ip/hsyncfifo_2048x24_afull1920.vhd
 -- Date	:	2024 07 15
 -- TD version	:	5.6.71036
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY hsyncfifo_2048x24_afull1920 IS
PORT (
	di	: IN STD_LOGIC_VECTOR(23 DOWNTO 0);

	rst	: IN STD_LOGIC;
	clk	: IN STD_LOGIC;
	we	: IN STD_LOGIC;
	re	: IN STD_LOGIC;
	do	: OUT STD_LOGIC_VECTOR(23 DOWNTO 0);
	empty_flag		: OUT STD_LOGIC;
	full_flag		: OUT STD_LOGIC;
	afull_flag		: OUT STD_LOGIC
	);
END hsyncfifo_2048x24_afull1920;

ARCHITECTURE struct OF hsyncfifo_2048x24_afull1920 IS

	BEGIN
	fifo_inst : EG_LOGIC_FIFO
		GENERIC MAP (
			DATA_WIDTH_W			=> 24,
			DATA_DEPTH_W			=> 2048,
			DATA_WIDTH_R			=> 24,
			DATA_DEPTH_R			=> 2048,
			ENDIAN				=> "LITTLE",
			RESETMODE			=> "ASYNC",
			REGMODE_R			=> "NOREG",
			E					=> 0,
			F					=> 2048,
			ASYNC_RESET_RELEASE	=> "ASYNC",
			AF					=> 1919
		)
		PORT MAP (
			rst	=> rst,
			di	=> di,
			clkw	=> clk,
			we	=> we,
			csw	=> "111",
			clkr	=> clk,
			ore	=> '0',
			re	=> re,
			csr	=> "111",
			do	=> do,
			empty_flag	=> empty_flag,
			aempty_flag	=> OPEN,
			full_flag	=> full_flag,
			afull_flag	=> afull_flag
		);

END struct;
